### ISSUE TITLE
message order

### ISSUE THREAD

**Issue by ghost** [DarkRiftNetworking/Hazel-Networking#3]
for (int i = 0; i < 100; i++)
{
      connection.SendBytes(Encoding.UTF8.GetBytes("____"+i), SendOption.Reliable);
}

recv data like this
____10
____1
____3
____4
____6
......

**Comment by ghost** [comment]
send finish callback?

**Comment by JamJar00** [comment]
Hi cathy33,

Hazel doesn't provide any guarantees about message order as a side effect of the multithreading it utilises. If ordering was implemented Hazel would need to completely scrap all the advantages the multithreading for ordered packets because otherwise the order could be changed at any time by a thread being disrupted.

If you need order then you could add a prefixing number of bytes to the start and then place the received messages into a priority queue which another thread can read off.

Send finish callbacks can be added, but it would be better if you could create a new issue for that so it can be tracked separately.

Jamie

**Comment by ghost** [comment]
ok, get it.  this library is wonderful for the game dev.

**Comment by JamJar00** [comment]
Thanks!

Jamie
